{"name": "Login User with Incorrect Credentials", "status": "passed", "description": "Verify error message appears when user logs in with invalid email/password.", "attachments": [{"name": "log", "source": "314a828b-a72b-4f1c-875a-5f74e3dde0e7-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "e4370751-0099-452d-b8ac-92c1d4dfa99c-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "e4dfba78-74dc-4a62-8cfc-d40a0f190ada-attachment.txt", "type": "text/plain"}], "start": 1748660471494, "stop": 1748660473879, "uuid": "4165731a-f472-4e82-9a1d-388fa42105ac", "historyId": "8dfedac07557eef94db876c5511d4142", "testCaseId": "8dfedac07557eef94db876c5511d4142", "fullName": "testCases.test_003_login_incorrect_credentials#test_003_login_user_with_incorrect_credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "User Authentication"}, {"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "test_003_login_incorrect_credentials"}, {"name": "host", "value": "DESKTOP-6JB123S"}, {"name": "thread", "value": "9356-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_003_login_incorrect_credentials"}]}