{"name": "Login User with Incorrect Credentials", "status": "passed", "description": "Verify error message appears when user logs in with invalid email/password.", "attachments": [{"name": "log", "source": "e665f154-1dcf-4725-91b0-4aa55d5c0b29-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "26013ee2-bc32-4763-a378-12daf11f3175-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "53072c82-49a8-44ee-a7b9-f78b73e43e32-attachment.txt", "type": "text/plain"}], "start": 1748366222678, "stop": 1748366225142, "uuid": "44f685fd-7c9d-42ba-949f-4f401f6824d6", "historyId": "8dfedac07557eef94db876c5511d4142", "testCaseId": "8dfedac07557eef94db876c5511d4142", "fullName": "testCases.test_003_login_incorrect_credentials#test_003_login_user_with_incorrect_credentials", "labels": [{"name": "feature", "value": "User Authentication"}, {"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "test_003_login_incorrect_credentials"}, {"name": "host", "value": "DESKTOP-6JB123S"}, {"name": "thread", "value": "8444-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_003_login_incorrect_credentials"}]}