{"name": "Login User with Incorrect Credentials", "status": "passed", "description": "Verify error message appears when user logs in with invalid email/password.", "attachments": [{"name": "log", "source": "0ba146de-148e-4875-92fe-c66327347625-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "52e49d50-eacb-49a3-ad41-72c2302d4b1e-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "19291ce8-89a9-478e-961b-dd5966358103-attachment.txt", "type": "text/plain"}], "start": 1748022529759, "stop": 1748022532053, "uuid": "cdd1a5b3-edec-496b-bf1b-ad670879d7fb", "historyId": "8dfedac07557eef94db876c5511d4142", "testCaseId": "8dfedac07557eef94db876c5511d4142", "fullName": "testCases.test_003_login_incorrect_credentials#test_003_login_user_with_incorrect_credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "User Authentication"}, {"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "test_003_login_incorrect_credentials"}, {"name": "host", "value": "DESKTOP-6JB123S"}, {"name": "thread", "value": "12592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_003_login_incorrect_credentials"}]}