{"name": "Login User with Incorrect Credentials", "status": "passed", "description": "Verify error message appears when user logs in with invalid email/password.", "attachments": [{"name": "log", "source": "e6b86db3-bbc1-438f-97d1-8c0b95632df3-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "72679c27-8574-4bd2-93fa-51dd56e5ec0a-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "afbdf8a7-37f5-4d86-a575-6a916d197b5c-attachment.txt", "type": "text/plain"}], "start": 1748369883650, "stop": 1748369885977, "uuid": "f7c14b17-92f6-4d07-898b-d13493169014", "historyId": "8dfedac07557eef94db876c5511d4142", "testCaseId": "8dfedac07557eef94db876c5511d4142", "fullName": "testCases.test_003_login_incorrect_credentials#test_003_login_user_with_incorrect_credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "User Authentication"}, {"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "test_003_login_incorrect_credentials"}, {"name": "host", "value": "DESKTOP-6JB123S"}, {"name": "thread", "value": "12744-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_003_login_incorrect_credentials"}]}