{"name": "Login User with Incorrect Credentials", "status": "passed", "description": "Verify error message appears when user logs in with invalid email/password.", "attachments": [{"name": "log", "source": "806e4610-1c76-42b5-84ae-562bcfc7eb11-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "35a8e0c2-839b-4044-8746-ecb5c330fd27-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "da72ac80-6553-4922-8932-99ba74a9aad5-attachment.txt", "type": "text/plain"}], "start": 1756621692758, "stop": 1756621694755, "uuid": "bf57fc27-a21a-45cf-89e9-0043462348a1", "historyId": "8dfedac07557eef94db876c5511d4142", "testCaseId": "8dfedac07557eef94db876c5511d4142", "fullName": "testCases.test_003_login_incorrect_credentials#test_003_login_user_with_incorrect_credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "User Authentication"}, {"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "test_003_login_incorrect_credentials"}, {"name": "host", "value": "DESKTOP-BT5T1BH"}, {"name": "thread", "value": "12320-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_003_login_incorrect_credentials"}]}